### ISSUE TITLE
303335

### ISSUE THREAD

**Issue by vahab-mspour** [awsdocs/amazon-personalize-developer-guide#13]
How can access to the values of the user and item embeddings or instead of their ranked score?
that is The numerator of the Sore(u,i)  or wt_u.w_i?
![image](https://user-images.githubusercontent.com/49309039/102978330-679e7600-4515-11eb-9306-a4b0d9a18e90.png)

**Comment by seashman** [comment]
You can only retrieve the ranked score - Personalize does not currently return the user and item embeddings themselves.
