### ISSUE TITLE
Quickstart link to install the SDK for Python (Boto3) not found

### ISSUE THREAD

**Issue by rbashish** [awsdocs/amazon-personalize-developer-guide#17]
While navigating to the link https://docs.aws.amazon.com/personalize/latest/dg/aws-personalize-set-up-sdks.html and clicking on the quickstart link shows  **Page Not Found** error.

Also, the[ GitHub page](https://github.com/awsdocs/amazon-personalize-developer-guide/blob/main/doc_source/aws-personalize-set-up-sdks.md) does not show the content itself as it does not have quickstart section as described in the main page.

Attach is the screenshot for reference:

![quickstart_aashishlive](https://user-images.githubusercontent.com/6831399/200616684-b94e4481-5f44-4d13-90ba-55dc848d8453.png)

![pnf](https://user-images.githubusercontent.com/6831399/200616727-3370fbdf-61be-4a9d-89e9-e983289229e5.png)

Please fix this.

**Comment by samashman** [comment]
Fixed link, updated markdown files in github

**Comment by rbashish** [comment]
Thanks, @samashman for fixing this!
