### ISSUE TITLE
Could be a mistake in the doc

### ISSUE THREAD

**Issue by StrangeParadise** [awsdocs/amazon-personalize-developer-guide#18]
Looks like the 'With User-Personalization, Amazon Personalize automatically updates your latest fully trained solution version (trained with trainingMode set to FULL) every two hours to include new items in recommendations with exploration.'

The 'with trainingMode set to UPDATE' should be 'with trainingMode set to UPDATE'?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
