### ISSUE TITLE
Incorrect guide step 14

### ISSUE THREAD

**Issue by Jarryd-rk** [awsdocs/amazon-personalize-developer-guide#2]
Steps 13 and 14 here:

https://docs.aws.amazon.com/personalize/latest/dg/aws-personalize-set-up-permissions.html

https://github.com/awsdocs/amazon-personalize-developer-guide/blob/master/doc_source/aws-personalize-set-up-permissions.md

Incorrectly guide customers to create an IAM policy and apply a bucket policy to an IAM role. 

This results in an error as principal is not recognised in IAM policies.

Step 13 is incorrect as you should navigate to the S3 console to apply the policy.

**Comment by seashman** [comment]
Text now refers to the Giving Amazon Personalize access to Amazon S3 resources topic https://docs.aws.amazon.com/personalize/latest/dg/granting-personalize-s3-access.html
