### ISSUE TITLE
Update policy in step 14

### ISSUE THREAD

**Issue by Jarryd-rk** [awsdocs/amazon-personalize-developer-guide#3]
The policy here

https://docs.aws.amazon.com/personalize/latest/dg/aws-personalize-set-up-permissions.html

https://github.com/awsdocs/amazon-personalize-developer-guide/blob/master/doc_source/aws-personalize-set-up-permissions.md

needs to be updated with PutObject permissions for the Batch recommendation feature

https://docs.aws.amazon.com/personalize/latest/dg/getting-recommendations.html#recommendations-batch

**Comment by seashman** [comment]
This is covered in the Giving Amazon Personalize access to Amazon S3 resources topic here:  https://github.com/awsdocs/amazon-personalize-developer-guide/blob/main/doc_source/granting-personalize-s3-access.md (https://docs.aws.amazon.com/personalize/latest/dg/granting-personalize-s3-access.html)
